### ISSUE TITLE
How to install this?

### ISSUE THREAD

**Issue by iCHAIT** [spilja/Subtitlr#1]

**Comment by smotesko** [comment]
@spilja any chance you publish it at the App Store?

**Comment by lucijafrkovic** [comment]
Nope, it got rejected due to possible copyright infringement (although
several other apps using OpenSubtitles.org API are available on the store).

Anyway, I'll build an installation file later today and report back here.

**Comment by lucijafrkovic** [comment]
@iCHAIT I'm not near my Mac now, but I found a build I made on Dropbox if you want to give it a try.
[Subtitlr dropbox link](https://www.dropbox.com/s/et60e6lcvi3h2qc/Subtitlr.zip?dl=0)

**Comment by iCHAIT** [comment]
@spilja  Thanks, works for me :+1:
